---
swagger: '2.0'
info:
  version: '0.1.0'
  title: Vality Payment Resource API
  description: >

    The Vality Payment Resource API is used to tokenize sensitive data of users' payment resources.
  termsOfService: https://vality.dev/
  contact:
    name: Support Team
    email: support@vality.dev
    url: https://vality.dev/
host: api.vality.dev
basePath: /payres/v0
schemes:
  - https
consumes:
  - application/json; charset=utf-8
produces:
  - application/json; charset=utf-8
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
    description: >
      Для аутентификации вызовов мы используем [JWT](https://jwt.io). Cоответствующий ключ передается в заголовке.
      ```shell Authorization: Bearer {TOKENIZATION|PRIVATE_JWT} ```
security:
  - 
    bearer: [ ]
responses:
  NotFound:
    description: Искомая сущность не найдена
  BadRequest:
    description: Недопустимые для операции входные данные
    schema:
      $ref: '#/definitions/BadRequest'
  Unauthorized:
    description: Ошибка авторизации
parameters:
  requestID:
    name: X-Request-ID
    in: header
    description: Уникальный идентификатор запроса к системе
    required: true
    type: string
    maxLength: 32
    minLength: 1
tags:
  - 
    name: Payment Resources
    x-displayName: Платёжные ресурсы
    description: ""
