---
swagger: "2.0"
info:
  version: "0.1.0"
  title: Vality Payment Resource API
  description: >

    The Vality Payment Resource API is used to tokenize sensitive data of users' payment resources.
  termsOfService: https://vality.dev/
  contact:
    name: Support Team
    email: support@vality.dev
    url: https://vality.dev/
host: api.vality.dev
basePath: /payres/v0
schemes:
  - https
consumes:
  - application/json; charset=utf-8
produces:
  - application/json; charset=utf-8
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
    description: >
      We use [JWT](https://jwt.io) for call authentication.
      The corresponding key is passed in the header.

      ```shell
       Authorization: Bearer {TOKENIZATION|PRIVATE_JWT}
      ```

security:
  - bearer: []
responses:
  NotFound:
    description: The content you are looking for was not found
  BadRequest:
    description: Invalid input data for operation
    schema:
      $ref: "#/definitions/BadRequest"
  Unauthorized:
    description: Authorization Error
parameters:
  requestID:
    name: X-Request-ID
    in: header
    description: Unique identifier of the request to the system
    required: true
    type: string
    maxLength: 32
    minLength: 1
tags:
  - name: Payment Resources
    x-displayName: Payment resources
    description: ""
