name: gh-pages
on:
  push:
    branches: [release/v0]

env:
  NODEJS_VERSION: '16'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: npm
      - run: npm install
      - name: Bundle specification
        run: npm run build
      - name: Publish ReDoc on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          exclude_assets: 'swagger-ui'
